# Generated by Django 3.2 on 2023-09-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cell',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternative Phone number'),
        ),
    ]
